In [6]:
pip install numpy

In [7]:
# Lets Import it
import numpy as np



In [6]:
a= 3
b= 4
c= a+b
c

7

In [5]:
np.__version__



'1.20.3'

In [3]:
print(np.__doc__) #docstring


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

In [4]:
print(np.array.__doc__)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly created array will be in C order (row major) unless 'F' is
        specifi

# Basic Features of NumPy

In [10]:
# Arange gives you range of values
# Only with end value
np.arange(101)

array([1,2,3])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
np.range(10)
0-10
range (10)

AttributeError: module 'numpy' has no attribute 'range'

In [15]:
#Creates an array for range of values between start & end number
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [9]:
# with start and end value with skip parameter
np.arange(100,9000,5)

array([ 100,  105,  110, ..., 8985, 8990, 8995])

In [16]:
# Linspace is used to create an array with values that are spaced linearly in a specified interval
# By default it creates 50 values
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
# with specific number of values
a=np.linspace(0,10,5)

In [20]:
#type(np.linspace(0,10))

type(a)

numpy.ndarray

# Random Data Generator Example

In [23]:
# Single Random Number
# 0-1
np.random.rand()

0.3039036265676195

In [32]:
# Multiple Random Number
a=np.random.rand(5,5) #2Dimentional Array
a

array([[0.80354398, 0.78407265, 0.53693683, 0.96229354, 0.97516044],
       [0.26325665, 0.1266216 , 0.96839953, 0.81451029, 0.91828307],
       [0.41160643, 0.99749121, 0.32850082, 0.18968785, 0.28918716],
       [0.09423329, 0.6671891 , 0.79855022, 0.27271359, 0.37359654],
       [0.71628001, 0.03971968, 0.32851606, 0.15563007, 0.70904603]])

In [17]:
# Return a sample (or samples) from the “standard normal” distribution.
np.random.randn(5,5)

array([[-0.95425459,  0.24495786,  0.44964794,  0.10178847, -0.31705575],
       [ 1.64767292,  2.08593109,  0.47370183, -0.02154886,  0.91273258],
       [-1.07055208,  0.39959088, -1.15720357, -0.39337254, -0.93203969],
       [ 0.56592941, -0.28128369,  1.44328746,  0.81190929, -0.45638202],
       [ 0.81124695,  1.02888487,  0.2007394 , -0.98911286,  0.31706969]])

In [34]:
# Return a sample (or samples) from the “standard normal” distribution.
# Multiple Numbers
np.random.randn(10)* 100

array([ 114.85582019,  -86.12569776,   99.84515486,  193.77501948,
       -173.44211402,  -18.81795658,    5.62007902,   -7.26484208,
        105.85270739,  -62.30070534])

In [40]:
# Single Random Integer Number
np.random.randint(2.9875)

1

In [22]:
np.random.randint(10,size=(20,10)) 

array([[2, 2, 0, 1, 9, 0, 6, 6, 0, 4],
       [6, 2, 3, 6, 4, 9, 9, 2, 4, 8],
       [4, 1, 6, 0, 6, 6, 6, 4, 3, 5],
       [9, 9, 0, 8, 9, 6, 5, 0, 1, 3],
       [4, 6, 6, 6, 7, 2, 6, 1, 0, 9],
       [5, 0, 7, 7, 5, 1, 4, 0, 1, 8],
       [3, 6, 1, 9, 2, 9, 3, 8, 6, 4],
       [0, 0, 8, 9, 1, 9, 7, 0, 3, 8],
       [4, 1, 6, 4, 6, 3, 4, 3, 3, 2],
       [8, 0, 3, 2, 6, 2, 7, 3, 2, 0],
       [1, 2, 8, 5, 3, 2, 9, 7, 0, 7],
       [2, 2, 3, 2, 0, 6, 9, 7, 1, 2],
       [1, 6, 9, 0, 4, 4, 6, 6, 3, 2],
       [3, 6, 1, 1, 0, 3, 6, 9, 9, 7],
       [2, 6, 5, 1, 3, 4, 5, 5, 5, 0],
       [0, 4, 1, 9, 8, 9, 7, 7, 6, 7],
       [5, 4, 2, 8, 9, 8, 7, 4, 6, 2],
       [6, 8, 9, 8, 7, 7, 1, 8, 7, 5],
       [4, 4, 7, 3, 4, 7, 4, 4, 7, 4],
       [8, 1, 8, 6, 0, 8, 5, 3, 0, 2]])

In [43]:
# Return random integers from low (inclusive) to high (exclusive).
# Random number from range
np.random.randint(10,15)

14

In [23]:
# Return random floats in the half-open interval [0.0, 1.0).
# alias for np.random.rand()
np.random.random_sample()

0.45701196201726857

In [14]:
# Return random floats in the half-open interval [0.0, 1.0).
# multiple values
np.random.random_sample(10)

array([0.61645925, 0.93445973, 0.5857006 , 0.07499554, 0.38636295,
       0.18700047, 0.74870788, 0.84667411, 0.42705183, 0.03046613])

In [22]:
#Return random floats in the half-open interval [0.0, 1.0]
np.random.random()

0.8874566224826035

In [23]:
#Return random floats in the half-open interval [0.0, 1.0]
np.random.random(10)

array([0.42198701, 0.5844209 , 0.52696329, 0.72606654, 0.23883519,
       0.15075901, 0.05246669, 0.27953919, 0.84698313, 0.30587893])

In [46]:
# Generates a random sample from a given 1-D array
a = np.array([1,2,3,4,5,6])
np.random.choice(a)

6

In [5]:
# They're just aliases to random_sample:

import numpy as np

np.random.random_sample is np.random.random
np.random.random_sample is np.random.rand
np.random.random_sample is np.random.sample

True

In [65]:
# Draw samples from a uniform distribution.
np.random.uniform()

0.5413911421113299

In [66]:
# Draw samples from a uniform distribution.
np.random.uniform(10,100,(3,5))

array([[78.40341778, 16.51496854, 97.77131483, 87.62421462, 34.55379349],
       [73.70260361, 72.7058137 , 17.55229076, 86.33890451, 43.21133933],
       [74.7965466 , 15.57138503, 72.41026279, 37.91871347, 56.96440953]])

# Create Array in Python

In [47]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

In [48]:
arr

array([1, 2, 3, 4, 5, 6])

In [49]:
type(arr)

numpy.ndarray

In [50]:
# shape of array or number of rows & Columns
arr.shape

(6,)

In [5]:
print(type(arr)) #Check the type of arr object

print(arr.ndim) #Check dimension of array

print(arr.size) #Check the size/number of elements in an array


<class 'numpy.ndarray'>
1
6


In [72]:
arr[0]

1

In [52]:
# higher value is exclusive
arr[0:3] #0,1,2

array([1, 2, 3])

In [53]:
# Lets create two dimensional arrays

a = np.array([[1,2,3,4],
              [5,7,8,9]])

In [54]:
a

array([[1, 2, 3, 4],
       [5, 7, 8, 9]])

In [93]:
type(a)

numpy.ndarray

In [94]:
a.shape

(2, 4)

In [95]:
a.ndim

2

In [96]:
a.size

8

In [55]:
# Get First record
a[0]

array([1, 2, 3, 4])

In [98]:
# Get second record
a[1]

array([5, 7, 8, 9])

In [99]:
# Get first element
a[0,0]

1

In [60]:
a[1,-1]

9

In [57]:
# Get first row and all columns skipping first
# Slicing of NP array
a[0,1:]

array([2, 3, 4])

In [26]:
# Get all Values
a[:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
# Get second row and all columns
a[1,:]

array([5, 7, 8, 9])

In [61]:
# Get second row and columns skipping first
a[::-1]

array([[5, 7, 8, 9],
       [1, 2, 3, 4]])

In [63]:
a

array([[1, 2, 3, 4],
       [5, 7, 8, 9]])

In [64]:
a[:,::-1]

array([[4, 3, 2, 1],
       [9, 8, 7, 5]])

# Create Array with alternatives

In [15]:
#Create an array with all elements as 0
print(np.zeros((4,4)))

#Create an array with all elements as 1
print(np.ones((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [49]:
# Create array with zeros's

a = np.zeros(2)
print(a)
print(a.shape)
print(a.ndim)

# two dimensional array
print()
print("Two dimensional array with Zeros")
a = np.zeros((2,2))
print(a)
print(a.shape)
print(a.ndim)

[0. 0.]
(2,)
1

Two dimensional array with Zeros
[[0. 0.]
 [0. 0.]]
(2, 2)
2


In [50]:
# Create array with one's

a = np.ones(2)
print(a)
print(a.shape)
print(a.ndim)

# two dimensional array
print()
print("Two dimensional array with Ones")
a = np.ones((3,6))
print(a)
print(a.shape)
print(a.ndim)

[1. 1.]
(2,)
1

Two dimensional array with Ones
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
(3, 6)
2


In [65]:
# Create EMPTY array
# The function empty creates an array whose initial content is random and depends on the state of the memory. 
# The reason to use empty over zeros (or something similar) is speed

np.empty(10)

array([ 1.72723371e-077,  4.34192928e-311,  3.83819517e+151,
        1.47721841e+179, -2.00390273e+000,  1.49457893e-154,
        1.48219694e-323,  0.00000000e+000,  0.00000000e+000,
        6.95335581e-309])

In [61]:
np.empty([10,5])

array([[0.47155684, 0.39430319, 1.18348493, 0.4160962 , 0.82960276],
       [0.09280334, 0.95696082, 1.14397718, 1.46944123, 0.46312116],
       [0.3871287 , 0.78076921, 1.28124489, 0.01308988, 0.27267169],
       [2.26385038, 1.24366794, 0.5101254 , 0.82441934, 0.84389436],
       [2.55171947, 1.71852358, 0.00339646, 1.26490569, 0.52257337],
       [1.24375796, 0.2459829 , 1.00990592, 0.35119477, 0.07284086],
       [1.51892285, 1.39096106, 0.83066606, 0.46386632, 1.20846369],
       [0.56868375, 0.43637265, 0.38108685, 1.82194477, 0.30646787],
       [0.28811815, 2.65453414, 0.65407258, 0.01677889, 1.80727313],
       [0.86708818, 0.37139163, 0.265926  , 0.49579494, 0.21833805]])

In [53]:
# Create array with specific value
# One dimension array
np.full(3,10)

array([10, 10, 10])

In [68]:
# Create two dimensional array with value 20
np.full((5,5),100,dtype='float')

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [75]:
# Create identity matrix
# Digonal will be 1
np.identity(15,dtype="int") * 13

array([[13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [77]:
a = np.identity((5),dtype='int')
np.fill_diagonal(a,13)
a

array([[13,  0,  0,  0,  0],
       [ 0, 13,  0,  0,  0],
       [ 0,  0, 13,  0,  0],
       [ 0,  0,  0, 13,  0],
       [ 0,  0,  0,  0, 13]])

# Create array with other data structures

In [55]:
# Create array from list
lst = [1,2,3,4,5,6]
arr = np.array(lst)

array([1, 2, 3, 4, 5, 6])

In [79]:
# Create array from tuple
tup = (1,2,3,4,5,6)
arr = np.array(tup)
arr[0] = 100
arr

array([100,   2,   3,   4,   5,   6])

# Operations on Array

In [1]:
import numpy as np
# Sorting an Array
# 1D array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
# Sorting an Array
# 2D array
arr = np.array([[2, 1, 5, 3],[7, 4, 6, 8]])
np.sort(arr)

array([[1, 2, 3, 5],
       [4, 6, 7, 8]])

In [2]:
# Finding largest value by index number

arr = np.array([10,2, 1, 5, 3, 7, 4, 6, 8])
ind = np.argmax(arr)
print("Index of largest value is :- ", ind)
print("largest value is :- ", arr[ind])

Index of largest value is :-  0
largest value is :-  10


In [125]:
# Finding smallest value by index number

arr = np.array([2, 1, 0, 5, 3, 7, 4, 6, 8])
ind = np.argmin(arr)
print("Index of smallest value is :- ", ind)
print("smallest value is :- ", arr[ind])

Index of smallest value is :-  2
smallest value is :-  0


In [71]:
# Find out max and min numbers instead of index

data = np.array([2, 1, 5, 3, 7, 4, 6, 8])
data.sort()
data[-3]

6

In [4]:
# Find out max and min numbers instead of index

data = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(data.min())
print(data.max())

1
8


In [5]:
# Find out total sum of all elements

data = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print(data.sum()) #sum
print(data.mean()) #Average

36
4.5


In [8]:
data = np.array([[2, 1, 5, 3],[ 7, 4, 6, 8]])
data

array([[2, 1, 5, 3],
       [7, 4, 6, 8]])

In [10]:
# Row wise mean
np.mean(data,axis=1)

array([2.75, 6.25])

In [11]:
# Column wise mean
np.mean(data,axis=0)

array([4.5, 2.5, 5.5, 5.5])

In [131]:
# Swapping two rows
# Change the index value

data[::-1]

array([[7, 4, 6, 8],
       [2, 1, 5, 3]])

In [23]:
# Concatenate two arrays
# 1D array

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
# Concatenation of 2D arrays

a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

# By default it will merge with existing format (on column Level)
np.concatenate((a, b),axis=0) #-----> np.vstack()

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
# Concatenation of 2D arrays

a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6], [7, 8]])

# axis 1 addes for rows
np.concatenate((a, b),axis=1) #-----> np.hstack()

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Reshaping of Array

In [67]:
# Using reshape() will can give a new shape to an array without changing the data. 
# Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements 
# as the original array.

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [27]:
a.shape

(6,)

In [31]:
# First parameter is number of rows
# Second parameter is number of columns
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [142]:
b = np.random.random(10)
b

array([0.63642186, 0.05706982, 0.92297576, 0.77531419, 0.60116672,
       0.46259019, 0.94328849, 0.63217271, 0.47449019, 0.79975662])

In [143]:
b.reshape(2,5)

array([[0.63642186, 0.05706982, 0.92297576, 0.77531419, 0.60116672],
       [0.46259019, 0.94328849, 0.63217271, 0.47449019, 0.79975662]])

In [144]:
# Conditional selection of elements
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [145]:
a.ndim

2

In [83]:
a > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [84]:
a[ a>5 ]

array([ 6,  7,  8,  9, 10, 11, 12])

In [76]:
# another way using variable

divisible_by_2 = a[ a%2==0 ]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [77]:
# Another example

c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [78]:
# Stacking of array

a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])

In [79]:
# In the background it calls for concatenation ONLY
np.vstack((a1, a2)) #----> np.concat(,axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [80]:
np.concatenate([a1,a2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [81]:
np.hstack((a1, a2)) #-----> np.concat(,axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# Broadcasting

## There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. 

## This concept is called broadcasting.

In [82]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [83]:
data = np.arange(10,100)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [84]:
data + 100

array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
       123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
       136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
       149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
       162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
       175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187,
       188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199])

In [85]:
data - 100

array([-90, -89, -88, -87, -86, -85, -84, -83, -82, -81, -80, -79, -78,
       -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66, -65,
       -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53, -52,
       -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39,
       -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26,
       -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [86]:
data * 8

array([ 80,  88,  96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176,
       184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280,
       288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384,
       392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488,
       496, 504, 512, 520, 528, 536, 544, 552, 560, 568, 576, 584, 592,
       600, 608, 616, 624, 632, 640, 648, 656, 664, 672, 680, 688, 696,
       704, 712, 720, 728, 736, 744, 752, 760, 768, 776, 784, 792])

# Matrix manipulation in Python

## A matrix is a two-dimensional data structure where numbers are arranged into rows and columns. 

In [32]:
# Two matrices are initialized by value
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

In [33]:
x

array([[1, 2],
       [4, 5]])

In [34]:
y

array([[ 7,  8],
       [ 9, 10]])

In [88]:
print("Addition of two matrices: ")
print(np.add(x,y))

Addition of two matrices: 
[[ 8 10]
 [13 15]]


In [88]:
x + y

array([[ 8, 10],
       [13, 15]])

In [89]:
print("Subtraction of two matrices : ")
print(np.subtract(x,y))

Subtraction of two matrices : 
[[-6 -6]
 [-5 -5]]


In [35]:
print("Matrix Division : ")
print(np.divide(x,y))

Matrix Division : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [36]:
x

array([[1, 2],
       [4, 5]])

In [37]:
y

array([[ 7,  8],
       [ 9, 10]])

In [70]:
# Numpy multiply or * will do elementwise multiplication

print("Multiplication of two matrices: ")
print(np.multiply(x,y))

Multiplication of two matrices: 
[[ 7 16]
 [36 50]]


In [38]:
x * y

array([[ 7, 16],
       [36, 50]])

In [92]:
# Numpy dot will do vector (pure matrix) multiplication 

print("The product of two matrices : ")
print(np.dot(x,y))

The product of two matrices : 
[[25 28]
 [73 82]]


In [93]:
print("square root is : ")
print(np.sqrt(x))

square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]


In [94]:
print("The summation of elements : ")
print(np.sum(y))

The summation of elements : 
34


In [95]:
print("The column wise summation  : ")
print(y)
print("\n")
print(np.sum(y,axis=0))

The column wise summation  : 
[[ 7  8]
 [ 9 10]]


[16 18]


In [96]:
print("The row wise summation: ")
print(np.sum(y,axis=1))

The row wise summation: 
[15 19]


In [97]:
# using "T" to transpose the matrix
print("Matrix transposition : ")
print("Original X")
print(x)
print("\n")
print(x.T)

Matrix transposition : 
Original X
[[1 2]
 [4 5]]


[[1 4]
 [2 5]]


# Tile Example

## numpy.tile(arr, repetitions) : constructs a new array by repeating array – ‘arr’, the number of times we want to repeat as per repetitions. 

In [39]:
arr = np.arange(5) #0-4

repetitions = 2
print("Repeating arr 2 times : \n", np.tile(arr, repetitions)) 
  
repetitions = 3
print("\nRepeating arr 3 times : \n", np.tile(arr, repetitions)) 

Repeating arr 2 times : 
 [0 1 2 3 4 0 1 2 3 4]

Repeating arr 3 times : 
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
